/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S_Fiches;

import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sondage.Openquestion;
import sondage.Qcm;
import sondage.Question;
import sondage.Questionnaire;
import sondage.Site_sondage;
import sondage.Table_mode;
import sondage.Teacher;

/**
 *
 * @author theobaptiste
 */
public class S_AfficherS extends javax.swing.JDialog {

    /**
     * Creates new form S_AfficherS
     */
    private Site_sondage site;
    private String nomSondageAffiche;
    private List<String> Participants = new ArrayList<String>(); 
    private List<Integer> Scores = new ArrayList<Integer>();
    private List<String> reponse = new ArrayList<String>();
    private List<Question> questions = new ArrayList<Question>();
    private int compteurQuest = 1;
    private int compteurParticipant = 1;
    private static S_MenuProf fichMenuProfConnecte;
    
    public S_AfficherS(java.awt.Frame parent, boolean modal, Site_sondage monSite, S_MenuProf menuProfConnecte) {
        super(parent, modal);
        initComponents();
        site = monSite;
        fichMenuProfConnecte = menuProfConnecte;
        jLabAffichageNomS.setVisible(false);
        jLabel1.setVisible(false);
        jLabNomProfRespo.setVisible(false);
        jLabNumQuestion.setVisible(false);
        jLabel2.setVisible(false);
        jLabTypeQuestion.setVisible(false);
        jLabIntituleQuest.setVisible(false);
        jLabTypeQuestion.setVisible(false);
        bAfficherReponseQcm.setVisible(false);
        jLabParticipantMail.setVisible(false);
        jLabParticipantNum.setVisible(false);
        bQuestionSuivante.setVisible(false);
        reponseAffiche.setVisible(false);
        bParticipantSuivant.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tfNomSondageAffiche = new javax.swing.JTextField();
        jLabGetNomSondageAffiche = new javax.swing.JLabel();
        validerNomSondageAffiche = new javax.swing.JButton();
        jLabAffichageNomS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabNomProfRespo = new javax.swing.JLabel();
        jLabIntituleQuest = new javax.swing.JLabel();
        jLabNumQuestion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabTypeQuestion = new javax.swing.JLabel();
        bAfficherReponseQcm = new javax.swing.JButton();
        bQuestionSuivante = new javax.swing.JButton();
        jLabParticipantNum = new javax.swing.JLabel();
        jLabParticipantMail = new javax.swing.JLabel();
        bParticipantSuivant = new javax.swing.JButton();
        bQuitter = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        reponseAffiche = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(220, 220, 253));

        tfNomSondageAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomSondageAfficheActionPerformed(evt);
            }
        });

        jLabGetNomSondageAffiche.setText("Entrez le nom du sondage à afficher :");
        jLabGetNomSondageAffiche.setOpaque(true);

        validerNomSondageAffiche.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        validerNomSondageAffiche.setText("✓");
        validerNomSondageAffiche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerNomSondageAfficheActionPerformed(evt);
            }
        });

        jLabAffichageNomS.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabAffichageNomS.setOpaque(true);

        jLabel1.setText("Professeur responsable du sondage :");
        jLabel1.setOpaque(true);

        jLabNomProfRespo.setText("     ");
        jLabNomProfRespo.setOpaque(true);

        jLabIntituleQuest.setText("    ");
        jLabIntituleQuest.setOpaque(true);

        jLabNumQuestion.setText("  ");
        jLabNumQuestion.setOpaque(true);

        jLabel2.setText("     Type de la question :");
        jLabel2.setOpaque(true);

        jLabTypeQuestion.setText("  ");
        jLabTypeQuestion.setOpaque(true);

        bAfficherReponseQcm.setText("Appuyer ici pour visualiser les réponses prédéfinies");
        bAfficherReponseQcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfficherReponseQcmActionPerformed(evt);
            }
        });

        bQuestionSuivante.setText("Appuyer ici pour afficher la question suivante du sondage");
        bQuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestionSuivanteActionPerformed(evt);
            }
        });

        jLabParticipantNum.setText("  ");
        jLabParticipantNum.setOpaque(true);

        jLabParticipantMail.setText(" ");
        jLabParticipantMail.setOpaque(true);

        bParticipantSuivant.setText("Participant suivant");
        bParticipantSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParticipantSuivantActionPerformed(evt);
            }
        });

        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        reponseAffiche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reponseAffiche.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                reponseAfficheAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(reponseAffiche);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabNumQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabIntituleQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabAffichageNomS, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabNomProfRespo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabTypeQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bAfficherReponseQcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bQuestionSuivante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabParticipantNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bParticipantSuivant)
                            .addComponent(jLabParticipantMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabGetNomSondageAffiche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfNomSondageAffiche, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validerNomSondageAffiche)))
                        .addGap(123, 123, 123)
                        .addComponent(bQuitter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabGetNomSondageAffiche)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(validerNomSondageAffiche)
                                    .addComponent(tfNomSondageAffiche, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bQuitter))
                        .addGap(18, 18, 18)
                        .addComponent(jLabAffichageNomS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabNomProfRespo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabIntituleQuest, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabNumQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jLabTypeQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAfficherReponseQcm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bQuestionSuivante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabParticipantNum, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabParticipantMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bParticipantSuivant)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerNomSondageModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerNomSondageModifActionPerformed

    }//GEN-LAST:event_validerNomSondageModifActionPerformed

    private void validerNomSondageAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerNomSondageAfficheActionPerformed
        // TODO add your handling code here:
        nomSondageAffiche = tfNomSondageAffiche.getText();
        if (site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageAffiche)==null){
            JOptionPane.showMessageDialog(this, "Le nom rentré ne correspond à aucun sondage", "Erreur introuvable", WIDTH);   
        }
        else{
            tfNomSondageAffiche.setVisible(false);
            validerNomSondageAffiche.setVisible(false);
            jLabGetNomSondageAffiche.setVisible(false);
            jLabAffichageNomS.setText(nomSondageAffiche);
            jLabAffichageNomS.setVisible(true);
            jLabel1.setVisible(true);
            jLabNomProfRespo.setText(S_ConnexionEns.getProfConnecte().getMail());
            jLabNomProfRespo.setVisible(true);
            jLabNumQuestion.setText("Question numéro 1 : ");
            jLabNumQuestion.setVisible(true);
            jLabel2.setVisible(true);
            jLabTypeQuestion.setVisible(true);
            bQuestionSuivante.setVisible(true);
            
            jLabParticipantMail.setText(site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageAffiche).getListeParticipants().get(0));
            jLabParticipantMail.setVisible(true);
            jLabParticipantNum.setText("Participant numéro 1 : ");
            jLabParticipantNum.setVisible(true);
            bParticipantSuivant.setVisible(true);
            
            questions = site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageAffiche).getListeQuestion();

                if (questions.get(0).getClass()==Openquestion.class){
                    jLabIntituleQuest.setText(questions.get(0).getIntituleQuest());
                    jLabTypeQuestion.setText("Question à réponse ouverte");    
                }
                else if (questions.get(0).getClass()==Qcm.class){
                    jLabIntituleQuest.setText(questions.get(0).getIntituleQuest());
                    jLabTypeQuestion.setText("Question à reponses prédéfinies");
                    bAfficherReponseQcm.setVisible(true); 
                }
            
            jLabIntituleQuest.setVisible(true);
            jLabTypeQuestion.setVisible(true);
        }
        tfNomSondageAffiche.setText(null);
    }//GEN-LAST:event_validerNomSondageAfficheActionPerformed

    private void tfNomSondageAfficheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomSondageAfficheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomSondageAfficheActionPerformed

    private void bAfficherReponseQcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfficherReponseQcmActionPerformed
        // TODO add your handling code here:
        reponseAffiche = new JTable (new Table_mode (questions.get(compteurQuest).getListRep(), questions.get(compteurQuest).getListScore()));
        reponseAffiche.setVisible(true);
    }//GEN-LAST:event_bAfficherReponseQcmActionPerformed

    private void bQuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestionSuivanteActionPerformed
        // TODO add your handling code here:
        if (questions.get(compteurQuest).getClass()==Openquestion.class){
                    jLabIntituleQuest.setText(questions.get(compteurQuest).getIntituleQuest());
                    jLabTypeQuestion.setText("Question à réponse ouverte");  
                    bAfficherReponseQcm.setVisible(false);
                }
        else if (questions.get(compteurQuest).getClass()==Qcm.class){
                    jLabIntituleQuest.setText(questions.get(compteurQuest).getIntituleQuest());
                    jLabTypeQuestion.setText("Question à reponses prédéfinies");
                    bAfficherReponseQcm.setVisible(true);
                }
        compteurQuest+=1;
        if (compteurQuest==questions.size()){
            compteurQuest=0;
        }
        
    }//GEN-LAST:event_bQuestionSuivanteActionPerformed

    private void bParticipantSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParticipantSuivantActionPerformed
        // TODO add your handling code here:
        jLabParticipantMail.setText(site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageAffiche).getListeParticipants().get(compteurParticipant));
        jLabParticipantMail.setVisible(true);
        jLabParticipantNum.setText("Participant numéro " + (compteurParticipant+1) + " : ");
        jLabParticipantNum.setVisible(true);
        compteurParticipant+=1;
        if (compteurParticipant>site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageAffiche).getListeParticipants().size()){
            compteurParticipant = 0;
        }
    }//GEN-LAST:event_bParticipantSuivantActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        fichMenuProfConnecte.setVisible(true);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void reponseAfficheAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_reponseAfficheAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_reponseAfficheAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_AfficherS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_AfficherS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_AfficherS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_AfficherS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                S_AfficherS dialog = new S_AfficherS(new javax.swing.JFrame(), true, S_Accueil.getSite(), fichMenuProfConnecte);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAfficherReponseQcm;
    private javax.swing.JButton bParticipantSuivant;
    private javax.swing.JButton bQuestionSuivante;
    private javax.swing.JButton bQuitter;
    private javax.swing.JLabel jLabAffichageNomS;
    private javax.swing.JLabel jLabGetNomSondageAffiche;
    private javax.swing.JLabel jLabIntituleQuest;
    private javax.swing.JLabel jLabNomProfRespo;
    private javax.swing.JLabel jLabNumQuestion;
    private javax.swing.JLabel jLabParticipantMail;
    private javax.swing.JLabel jLabParticipantNum;
    private javax.swing.JLabel jLabTypeQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable reponseAffiche;
    private javax.swing.JTextField tfNomSondageAffiche;
    private javax.swing.JButton validerNomSondageAffiche;
    // End of variables declaration//GEN-END:variables
}
