/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S_Fiches;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import sondage.Openquestion;
import sondage.Openreponse;
import sondage.Qcm;
import sondage.Questionnaire;
import sondage.Reponse;
import sondage.Site_sondage;
import sondage.Student;
import sondage.Table_mode_etu;

/**
 *
 * @author theobaptiste
 */
public class S_Etudiant extends javax.swing.JDialog {

    /**
     * Creates new form S_Etudiant
     */
    private Site_sondage site;
    private Student eleveConnecte;
    private List<Reponse> Reponses = new ArrayList<Reponse>();
    private Questionnaire jouerSondage;
    private int compteurQuest = 1;
    
    public S_Etudiant(java.awt.Frame parent, boolean modal, Site_sondage monSite) {
        super(parent, modal);
        initComponents();
        site = monSite;
        bValiderCode.setVisible(true);
        jLabMenuEtu.setVisible(true);
        jLabRentrezCode.setVisible(true);
        tfCode.setVisible(true);
        jLabRentrezVotreMail.setVisible(false);
        tfEmailEtu.setVisible(false);
        bValiderMailParticipant.setVisible(false);
        jLabNumeroQuest.setVisible(false);
        jLabIntituleQuest.setVisible(false);
        jLabTypeQuest.setVisible(false);
        tfInsertionReponse.setVisible(false);
        bAfficherRepQcm.setVisible(false);
        bQuestionSuivante.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabRentrezVotreMail = new javax.swing.JLabel();
        jLabRentrezCode = new javax.swing.JLabel();
        tfEmailEtu = new javax.swing.JTextField();
        tfCode = new javax.swing.JTextField();
        bValiderCode = new javax.swing.JButton();
        jLabMenuEtu = new javax.swing.JLabel();
        bValiderMailParticipant = new javax.swing.JButton();
        jLabNumeroQuest = new javax.swing.JLabel();
        jLabIntituleQuest = new javax.swing.JLabel();
        tfInsertionReponse = new javax.swing.JTextField();
        jLabTypeQuest = new javax.swing.JLabel();
        bAfficherRepQcm = new javax.swing.JButton();
        bQuestionSuivante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(220, 220, 253));

        jLabRentrezVotreMail.setText("Rentrez votre mail");

        jLabRentrezCode.setText("Rentrez le code ");

        bValiderCode.setText("Valider");
        bValiderCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderCodeActionPerformed(evt);
            }
        });

        jLabMenuEtu.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabMenuEtu.setText("Menu Etudiant");

        bValiderMailParticipant.setText("Valider");
        bValiderMailParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderMailParticipantActionPerformed(evt);
            }
        });

        jLabNumeroQuest.setText(" ");
        jLabNumeroQuest.setOpaque(true);

        jLabIntituleQuest.setText("  ");
        jLabIntituleQuest.setOpaque(true);

        tfInsertionReponse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfInsertionReponseMouseClicked(evt);
            }
        });

        jLabTypeQuest.setText("  ");
        jLabTypeQuest.setOpaque(true);

        bAfficherRepQcm.setText("Afficher réponses possibles");
        bAfficherRepQcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAfficherRepQcmActionPerformed(evt);
            }
        });

        bQuestionSuivante.setText("Valider la réponse et passer à la question suivante ");
        bQuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestionSuivanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabMenuEtu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabRentrezVotreMail)
                    .addComponent(jLabRentrezCode))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bValiderCode))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfEmailEtu, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bValiderMailParticipant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(129, 129, 129))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabNumeroQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabTypeQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAfficherRepQcm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabIntituleQuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfInsertionReponse)
                    .addComponent(bQuestionSuivante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabMenuEtu)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabRentrezCode)
                    .addComponent(tfCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bValiderCode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabRentrezVotreMail)
                    .addComponent(tfEmailEtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bValiderMailParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNumeroQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabTypeQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAfficherRepQcm))
                .addGap(18, 18, 18)
                .addComponent(jLabIntituleQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfInsertionReponse, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bQuestionSuivante)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bValiderCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderCodeActionPerformed
        String Code = tfCode.getText();
        jouerSondage = site.codeSondage(Integer.valueOf(Code));
        if (jouerSondage==null){
            JOptionPane.showMessageDialog(this, "Le nom rentré ne correspond à aucun sondage", "Erreur introuvable", WIDTH);
        }
        else{
            if (jouerSondage.getAnonyme()==false){
                jLabRentrezVotreMail.setVisible(true);
                tfEmailEtu.setVisible(true);
                bValiderMailParticipant.setVisible(true);
            }
            else if (jouerSondage.getAnonyme()==true){
                eleveConnecte = new Student("anonyme");
            }
            jLabNumeroQuest.setText("Question numéro 1");
            jLabNumeroQuest.setVisible(true);
            jLabIntituleQuest.setText(jouerSondage.getListeQuestion().get(0).getIntituleQuest());
            jLabIntituleQuest.setVisible(true);
            bQuestionSuivante.setVisible(true);
            if (jouerSondage.getListeQuestion().get(0).getClass()==Openquestion.class){
                jLabTypeQuest.setText("Question à reponse ouverte");
                jLabTypeQuest.setVisible(true);
                tfInsertionReponse.setVisible(true);
                String answer = tfInsertionReponse.getText();
                Openreponse repOuverte = new Openreponse(0, eleveConnecte, answer);
                Reponses.add(repOuverte);
            }
            else if (jouerSondage.getListeQuestion().get(0).getClass()==Qcm.class){
                jLabTypeQuest.setText("Question à reponses prédéfinies");
                jLabTypeQuest.setVisible(true);
                bAfficherRepQcm.setVisible(true);
                tfInsertionReponse.setText("Pour les questions à réponses prédéfinies veuillez seulement entrer le numéro de la réponse choisie.");
                tfInsertionReponse.setVisible(true);
                int indiceRepChoisie = Integer.valueOf(tfInsertionReponse.getText());
                Reponse repQcm = new Reponse (0, indiceRepChoisie, eleveConnecte);
                Reponses.add(repQcm);
            }
            
        }
    }//GEN-LAST:event_bValiderCodeActionPerformed

    private void bValiderMailParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderMailParticipantActionPerformed
        // TODO add your handling code here:
        String mailParticipant = tfEmailEtu.getText();
        eleveConnecte = new Student(mailParticipant);
    }//GEN-LAST:event_bValiderMailParticipantActionPerformed

    private void bAfficherRepQcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAfficherRepQcmActionPerformed
        // TODO add your handling code here:
        JTable affichageRepQcm = new JTable (new Table_mode_etu(jouerSondage.getListeQuestion().get(compteurQuest-1).getListRep()));
        affichageRepQcm.setVisible(true);
    }//GEN-LAST:event_bAfficherRepQcmActionPerformed

    private void tfInsertionReponseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfInsertionReponseMouseClicked
        // TODO add your handling code here:
        tfInsertionReponse.setText("");
    }//GEN-LAST:event_tfInsertionReponseMouseClicked

    private void bQuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestionSuivanteActionPerformed
        // TODO add your handling code here:
        compteurQuest+=1;
        jLabNumeroQuest.setText("Question numéro " + (compteurQuest));
        jLabNumeroQuest.setVisible(true);
        jLabIntituleQuest.setText(jouerSondage.getListeQuestion().get(compteurQuest-1).getIntituleQuest());
        jLabIntituleQuest.setVisible(true);
        if (jouerSondage.getListeQuestion().get(compteurQuest-1).getClass()==Openquestion.class){
                jLabTypeQuest.setText("Question à reponse ouverte");
                jLabTypeQuest.setVisible(true);
                tfInsertionReponse.setVisible(true);
                String answer = tfInsertionReponse.getText();
                Openreponse repOuverte = new Openreponse(compteurQuest-1, eleveConnecte, answer);
                Reponses.add(repOuverte);
        }
        else if (jouerSondage.getListeQuestion().get(compteurQuest-1).getClass()==Qcm.class){
                jLabTypeQuest.setText("Question à reponses prédéfinies");
                jLabTypeQuest.setVisible(true);
                bAfficherRepQcm.setVisible(true);
                tfInsertionReponse.setText("Pour les questions à réponses prédéfinies veuillez seulement entrer le numéro de la réponse choisie.");
                tfInsertionReponse.setVisible(true);   
                int indiceRepChoisie = Integer.valueOf(tfInsertionReponse.getText());
                Reponse repQcm = new Reponse (compteurQuest-1, indiceRepChoisie, eleveConnecte);
                Reponses.add(repQcm);
        }
        bQuestionSuivante.setVisible(true);
        
        if (compteurQuest==jouerSondage.getListeQuestion().size()){
            JOptionPane.showMessageDialog(this, "Vous avez répondu à toutes les questions du sondage vous allez être redirigés vers la page d'accueil.", "Sondage terminé.", WIDTH);
            this.setVisible(false);
            this.getParent().setVisible(true);
        }
            
    }//GEN-LAST:event_bQuestionSuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                S_Etudiant dialog = new S_Etudiant(new javax.swing.JFrame(), true, S_Accueil.getSite());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAfficherRepQcm;
    private javax.swing.JButton bQuestionSuivante;
    private javax.swing.JButton bValiderCode;
    private javax.swing.JButton bValiderMailParticipant;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabIntituleQuest;
    private javax.swing.JLabel jLabMenuEtu;
    private javax.swing.JLabel jLabNumeroQuest;
    private javax.swing.JLabel jLabRentrezCode;
    private javax.swing.JLabel jLabRentrezVotreMail;
    private javax.swing.JLabel jLabTypeQuest;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfCode;
    private javax.swing.JTextField tfEmailEtu;
    private javax.swing.JTextField tfInsertionReponse;
    // End of variables declaration//GEN-END:variables
}
