/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S_Fiches;

import javax.swing.JOptionPane;
import sondage.Questionnaire;
import sondage.Site_sondage;

/**
 *
 * @author theobaptiste
 */
public class S_ModifierS extends javax.swing.JDialog {

    /**
     * Creates new form S_ModifierS
     */
    private Site_sondage site;
    
    public S_ModifierS(java.awt.Frame parent, boolean modal, Site_sondage monSite) {
        super(parent, modal);
        initComponents();
        site = monSite;
        AjouterQcm.setVisible(false);
        ajouterQO.setVisible(false);
        bAjoutParticipant.setVisible(false);
        bNewN.setVisible(false);
        bSuppSondage.setVisible(false);
        tfAjoutQO.setVisible(false);
        tfAjoutQcm.setVisible(false);
        tfAjouterParticipant.setVisible(false);
        tfNewN.setVisible(false);
        validerAjoutParticipant.setVisible(false);
        validerAjoutQCM1.setVisible(false);
        validerAjoutQO.setVisible(false);
        validerChangementNom.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNewN = new javax.swing.JTextField();
        tfNomSondageModif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        validerNomSondageModif = new javax.swing.JButton();
        tfAjouterParticipant = new javax.swing.JTextField();
        tfAjoutQO = new javax.swing.JTextField();
        tfAjoutQcm = new javax.swing.JTextField();
        validerAjoutQO = new javax.swing.JButton();
        validerChangementNom = new javax.swing.JButton();
        validerAjoutQCM1 = new javax.swing.JButton();
        validerAjoutParticipant = new javax.swing.JButton();
        jLabModifNom = new javax.swing.JLabel();
        jLabAjoutParticipant = new javax.swing.JLabel();
        jLabAjoutQcm = new javax.swing.JLabel();
        jLabAjoutQO = new javax.swing.JLabel();
        bSuppSondage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("V euillez entrer le nom du sondage à modifier :");

        validerNomSondageModif.setText("Valider");
        validerNomSondageModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerNomSondageModifActionPerformed(evt);
            }
        });

        validerAjoutQO.setText("✓");

        validerChangementNom.setText("✓");

        validerAjoutQCM1.setText("✓");

        validerAjoutParticipant.setText("✓");

        jLabModifNom.setText("Modifier le nom du sondage");

        jLabAjoutParticipant.setText("Ajouter un participant");

        jLabAjoutQcm.setText("Ajouter un QCM");

        jLabAjoutQO.setText("Ajouter une question ouverte");

        bSuppSondage.setText("Supprimer le sondage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNomSondageModif, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(validerNomSondageModif)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfAjoutQcm, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validerAjoutQCM1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(tfAjoutQO, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validerAjoutQO)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNewN, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validerChangementNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfAjouterParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validerAjoutParticipant)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabModifNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabAjoutParticipant)
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabAjoutQcm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabAjoutQO)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(bSuppSondage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomSondageModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerNomSondageModif))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabModifNom)
                    .addComponent(jLabAjoutParticipant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNewN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAjouterParticipant, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerChangementNom)
                    .addComponent(validerAjoutParticipant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(bSuppSondage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabAjoutQcm)
                    .addComponent(jLabAjoutQO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAjoutQO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAjoutQcm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerAjoutQO)
                    .addComponent(validerAjoutQCM1))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerNomSondageModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerNomSondageModifActionPerformed
        // TODO add your handling code here:
        String nomSondageModif = tfNomSondageModif.getText();
        Questionnaire sondageAmodifier = site.searchSondage(S_ConnexionEns.getProfConnecte().getMail(), nomSondageModif);
        if (sondageAmodifier == null){
            JOptionPane.showMessageDialog(this, "Le nom rentré ne correspond à aucun sondage", "Erreur introuvable", WIDTH);
        }
        else {
            jLabAjoutQcm.setVisible(true);
            jLabAjoutQO.setVisible(true);
            jLabAjoutParticipant.setVisible(true);
            jLabModifNom.setVisible(true);
            bSuppSondage.setVisible(true);
            tfAjoutQO.setVisible(true);
            tfAjoutQcm.setVisible(true);
            tfAjouterParticipant.setVisible(true);
            tfNewN.setVisible(true);
            validerAjoutParticipant.setVisible(true);
            validerAjoutQCM1.setVisible(true);
            validerAjoutQO.setVisible(true);
            validerChangementNom.setVisible(true);
        }
    }//GEN-LAST:event_validerNomSondageModifActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_ModifierS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_ModifierS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_ModifierS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_ModifierS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                S_ModifierS dialog = new S_ModifierS(new javax.swing.JFrame(), true, S_Accueil.getSite());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSuppSondage;
    private javax.swing.JLabel jLabAjoutParticipant;
    private javax.swing.JLabel jLabAjoutQO;
    private javax.swing.JLabel jLabAjoutQcm;
    private javax.swing.JLabel jLabModifNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tfAjoutQO;
    private javax.swing.JTextField tfAjoutQcm;
    private javax.swing.JTextField tfAjouterParticipant;
    private javax.swing.JTextField tfNewN;
    private javax.swing.JTextField tfNomSondageModif;
    private javax.swing.JButton validerAjoutParticipant;
    private javax.swing.JButton validerAjoutQCM1;
    private javax.swing.JButton validerAjoutQO;
    private javax.swing.JButton validerChangementNom;
    private javax.swing.JButton validerNomSondageModif;
    // End of variables declaration//GEN-END:variables
}
